# Generated by Django 3.0.3 on 2020-03-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisory',
            options={'verbose_name_plural': 'Advisories'},
        ),
        migrations.AlterModelOptions(
            name='awareness',
            options={'verbose_name_plural': 'Awarenesses'},
        ),
    ]
