# Generated by Django 3.0.3 on 2020-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200326_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govtdata',
            name='infected',
        ),
        migrations.AddField(
            model_name='advisory',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='govtdata',
            name='cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='govtdata',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='govtdata',
            name='international',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='govtdata',
            name='is_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='govtdata',
            name='national',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='govtdata',
            name='cured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='govtdata',
            name='death',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='govtdata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
