# Generated by Django 3.0.3 on 2020-04-05 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20200405_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govtdata',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='govtdata',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
