# Generated by Django 3.0.3 on 2020-04-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_precaution_is_lockdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('aadhar', models.BigIntegerField()),
                ('withdrawl', models.DateField()),
                ('distance', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
