# Generated by Django 3.0.3 on 2020-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
