# Generated by Django 3.0.3 on 2020-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('doctor_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
    ]
