# Generated by Django 3.0.3 on 2020-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0005_auto_20200320_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='travelled',
            field=models.BooleanField(default=False),
        ),
    ]
