# Generated by Django 3.0.3 on 2020-03-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0007_auto_20200322_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
