# Generated by Django 3.0.3 on 2020-03-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0008_auto_20200323_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpline',
            name='lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
