# Generated by Django 3.0.3 on 2020-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0010_auto_20200326_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingcenter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
