# Generated by Django 3.0.3 on 2020-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0011_testingcenter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(default='asd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(default='asdfghj', max_length=50),
            preserve_default=False,
        ),
    ]
