# Generated by Django 3.0.3 on 2020-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0012_auto_20200326_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='cured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_infected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='travelled',
            field=models.BooleanField(default=False),
        ),
    ]
