# Generated by Django 3.0.3 on 2020-04-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0014_auto_20200326_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='death',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
