# Generated by Django 3.0.3 on 2020-04-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0015_auto_20200403_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingcenter',
            name='cat',
            field=models.CharField(choices=[('TC', 'TC'), ('SC', 'SC'), ('PR', 'PR')], default='TC', max_length=2),
            preserve_default=False,
        ),
    ]
