# Generated by Django 3.0.3 on 2020-04-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0016_testingcenter_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpline',
            old_name='contact',
            new_name='contact1',
        ),
        migrations.AddField(
            model_name='helpline',
            name='contact2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpline',
            name='contact3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpline',
            name='contact4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='decl_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
