# Generated by Django 3.0.3 on 2020-04-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0018_auto_20200406_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='idk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='isolated',
            field=models.BooleanField(default=False),
        ),
    ]
