# Generated by Django 3.0.3 on 2020-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidApp', '0019_auto_20200410_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
